# Generated by Django 3.2.2 on 2021-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pl1.png', upload_to='img'),
            preserve_default=False,
        ),
    ]
